[package]
name = "mikomikagi"
build = "build.rs"
description.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

default-run = "mikomikagi"

[features]
std = ["blake3/std"]

[dependencies]
mikomikagi-tui 		= { workspace = true }
mikomikagi-schemes 	= { workspace = true }
mikomikagi-keyring 	= { workspace = true }
mikomikagi-core 	= { workspace = true }
mikomikagi-lib 		= { workspace = true }

clap 				= { workspace = true }
clap_complete 		= { workspace = true }
crossterm 			= { workspace = true }
simple_logger 		= { workspace = true }
log 				= { workspace = true }
pem 				= { workspace = true }
borsh 				= { workspace = true }
base64 				= { workspace = true }
heed 				= { workspace = true }
hex 				= { workspace = true }
time 				= { workspace = true }
argon2 				= { workspace = true }
blake3 				= { workspace = true }
rand 				= { workspace = true }
zalloc 				= { workspace = true }

[build-dependencies]
clap 				= { workspace = true }
clap_complete 		= { workspace = true }
hex 				= { workspace = true }
